### ISSUE TITLE
Lakka menu does not display well with mali-fbdev

### ISSUE THREAD

**Issue by Kivutar** [lakkatv/Lakka#103]
There are black areas.

**Comment by alexandrevicenzi** [comment]
Hi, any suggestion to solve this? I have a BPi, and I could take a look, but someone needs to point me where to start.

**Comment by Kivutar** [comment]
Yes, you can try one of those two things:

 * Setup arch linux for BPi, setup mali for framebuffer, build retroarch from source, edit lakka.c in retroarch until you find a way to fix the bug
 * Setup arch linux for BPi, setup an alternate sunxi kernel with mali r4p0 driver, setup mali for framebuffer version r4p0 from odroid, build retroarch from source and see if it fixes the bug

**Comment by alexandrevicenzi** [comment]
OK. I will take a look.

**Comment by Kivutar** [comment]
You can join our IRC chan if you need live help for this

**Comment by Kivutar** [comment]
Fixed, will be available in the next nightly.

**Comment by alexandrevicenzi** [comment]
Oh, nice. I didn't have time to take a look :cry:
