### ISSUE TITLE
WandBoard: mednafen build error

### ISSUE THREAD

**Issue by xoddark** [lakkatv/Lakka#136]
Hello, when I try to build Lakka with Project WandBoard I got this error:

`mednafen/sound/OwlResampler.cpp: In member function 'OwlResampler::Resample(OwlBuffer*, unsigned int, short*, unsigned int)':
mednafen/sound/OwlResampler.cpp:512:2: error: impossible constraint in 'asm'`

**Comment by Kivutar** [comment]
Ok, I just guess that mednafen cores changed their names, since we use beetle cores instead. Just try to remane them. Those cores are listed under packages/lakka/WandBoard/package.mk dependancies. Take a look at the dependancies of the imx6 project and use the same.

**Comment by xoddark** [comment]
Hello, sorry for the respons delay, with same package for WandBoard than for imx6, I'm was able to build Lakka for WandBoard.

I wanted to make a pull request with the change, but because I already fork OpenElec.tv I wasn't able to fork Lakka.tv :(.

**Comment by Kivutar** [comment]
Good news! I wonder why you were not able to fork. Some contributors were able to fork, see https://github.com/recioalex/Lakka

Maybe you already own a fork of OpenELEC in your account?

**Comment by xoddark** [comment]
Yes it's the reason.
