### ISSUE TITLE
Cubox-i joypad exit button combination

### ISSUE THREAD

**Issue by ralias** [lakkatv/Lakka#142]
I can't  exit from the emulators with a joypad's buttons combination. I tried to do with:
input_enable_hotkey_btn = 7
input_exit_emulator_btn = 8

Seven is my select button and eight my start button. Seems that the hotkeys doesn't works. When I press start exit directly from the emulator.

**Comment by Kivutar** [comment]
Hello, is this way of configuring inputs supposed to work in RetroArch? Maybe you should ask RetroArch team on IRC, and try to make it work on your regular computer first.

@floreal any idea?

**Comment by Kivutar** [comment]
@ralias the new nightlies include this, can you try again please https://github.com/libretro/RetroArch/issues/1310

**Comment by ralias** [comment]
I cross compiled the last source code versuib and it's right. It's working perfectly!!
