### ISSUE TITLE
Fix NFS client on imx6

### ISSUE THREAD

**Issue by Kivutar** [lakkatv/Lakka#148]
Needs the right kernel options

**Comment by ralias** [comment]
Will be nice configure the mounted file system directly from a lakka's menu option. Mount/Unmount/Automount.

**Comment by Kivutar** [comment]
I agree, the goal is to have everything configurable using the menu : network, netplay, sharing, etc
However, the priority right now is getting the cores and the basic menu working on the supported platforms.
