### ISSUE TITLE
Cubox-i: 7z files in megadrive emulator

### ISSUE THREAD

**Issue by ralias** [lakkatv/Lakka#155]
I copy some megadrive roms i the ROM folder. This roms are compresed by 7z. I can see it it the lakka menu but doesn't work in the emulator. I also see this files in the PSP Emulator section. Is this kind of compressed files compatible with the Megadrive Emulator. Why I see it in the PSP section? I can do anything to avoid that? Thanks.

**Comment by Kivutar** [comment]
Do not use zipped roms for now, since the actual version of the menu relies on rom extentions as filter.
