### ISSUE TITLE
Common usage documentation

### ISSUE THREAD

**Issue by jlecour** [lakkatv/Lakka#74]
The `20140310093345-r17679-g0a5d263` image is working with my RaspberryPi and my Freebox joystick. It boots and I can navigate the menus, but there is obviously no content to use.

Is there somewhere a quick start documentation with instruction for finding and installing content?

Thanks for your great work on this.

**Comment by Kivutar** [comment]
The structure of the user documentation is ready now http://www.lakka.tv/doc/Home/
Some pages are still incomplete though.
